package view;

import com.intellij.ui.treeStructure.Tree;
import function.Debug;
import view.listInfoView.ChatInfoNode;
import view.listInfoView.ChatInfoNodeRender;

import javax.swing.*;
import javax.swing.event.MouseInputAdapter;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * 聊天主页
 */
public class ChatView {
    private JPanel panel1;
    private JEditorPane editorPane1;
    private JButton BT_Info;
    private JButton BT_QuitGroup;
    private JButton BT_DeleteFriend;
    private JButton BT_History;
    private JTextArea textArea1;
    private JPanel topSettingPanel;
    private JButton BT_AddFriend;
    private JButton BT_AddGroup;
    private JButton BT_Setting;
    private JButton BT_MemberList;
    private JScrollPane JSP_FriendList;
    /**
     * 一定要注意，这个必须要检查字符串长度，否则会导致问题
     */
    private JLabel LB_ChatObjTitle;
    private JTree tree1;

    private ChatInfoNode root;

    public ChatView() {
        JFrame asd = new JFrame();
        $$$setupUI$$$();
        asd.setVisible(true);
        asd.setSize(800, 600);
        asd.setLocationRelativeTo(null);
        asd.setResizable(false);
        asd.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        asd.getContentPane().setBackground(new Color(0x323436));
        asd.setTitle("聊天");

        asd.add($$$getRootComponent$$$());

        Color back = new Color(0xC2C2C2);

        root = new ChatInfoNode(back, "我的好友", "");
        for (int i = 0; i < 15; i++) {
            ChatInfoNode sub = new ChatInfoNode(back, "好友" + (i + 1), "你好你好你好你好", i % 2 == 0, false);


            root.add(sub);
        }

        tree1 = new JTree(root);
        tree1.setBackground(back);
        tree1.setDropMode(DropMode.ON);
        tree1.setOpaque(true);
        JSP_FriendList.setViewportView(tree1);

        //将树的前面连接去掉
        tree1.putClientProperty("JTree.lineStyle", "Horizontal");
        //设置树的字体大小，样式
        tree1.setFont(new Font("微软雅黑", Font.PLAIN, 1));
        //设置树节点的高度
        tree1.setRowHeight(70);
        //设置单元渲染描述
        tree1.setCellRenderer(new ChatInfoNodeRender());

        tree1.setRootVisible(false);

        tree1.addTreeSelectionListener(e ->
                editorPane1.setText(chatContent += ((ChatInfoNode)
                        tree1.getLastSelectedPathComponent()).getHead() + "\r\n")
        );

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setContinuousLayout(false);
        splitPane1.setDividerLocation(212);
        splitPane1.setEnabled(true);
        splitPane1.setForeground(new Color(-4473925));
        splitPane1.setOneTouchExpandable(false);
        splitPane1.setResizeWeight(0.5);
        panel1.add(splitPane1, BorderLayout.CENTER);
        JSP_FriendList = new JScrollPane();
        JSP_FriendList.setBackground(new Color(-12763327));
        JSP_FriendList.setVerticalScrollBarPolicy(22);
        splitPane1.setLeftComponent(JSP_FriendList);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        splitPane1.setRightComponent(panel2);
        final JSplitPane splitPane2 = new JSplitPane();
        splitPane2.setDividerLocation(208);
        splitPane2.setLastDividerLocation(227);
        splitPane2.setOrientation(0);
        splitPane2.setResizeWeight(0.5);
        panel2.add(splitPane2, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        splitPane2.setRightComponent(panel3);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        panel3.add(panel4, BorderLayout.NORTH);
        BT_MemberList = new JButton();
        BT_MemberList.setText("查看成员");
        panel4.add(BT_MemberList);
        BT_History = new JButton();
        BT_History.setHorizontalAlignment(0);
        BT_History.setHorizontalTextPosition(0);
        BT_History.setText("历史记录");
        BT_History.setVerticalAlignment(0);
        panel4.add(BT_History);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel3.add(scrollPane1, BorderLayout.CENTER);
        textArea1 = new JTextArea();
        scrollPane1.setViewportView(textArea1);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        splitPane2.setLeftComponent(panel5);
        final JScrollPane scrollPane2 = new JScrollPane();
        scrollPane2.setHorizontalScrollBarPolicy(30);
        scrollPane2.setVerticalScrollBarPolicy(20);
        panel5.add(scrollPane2, BorderLayout.CENTER);
        editorPane1 = new JEditorPane();
        editorPane1.setEditable(false);
        scrollPane2.setViewportView(editorPane1);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
        panel5.add(panel6, BorderLayout.NORTH);
        LB_ChatObjTitle = new JLabel();
        LB_ChatObjTitle.setEnabled(true);
        Font LB_ChatObjTitleFont = this.$$$getFont$$$(null, -1, 20, LB_ChatObjTitle.getFont());
        if (LB_ChatObjTitleFont != null) LB_ChatObjTitle.setFont(LB_ChatObjTitleFont);
        LB_ChatObjTitle.setText("聊天对象名称");
        panel6.add(LB_ChatObjTitle);
        BT_Info = new JButton();
        BT_Info.setHorizontalAlignment(0);
        BT_Info.setHorizontalTextPosition(0);
        BT_Info.setText("查看资料");
        BT_Info.setVerticalAlignment(0);
        panel6.add(BT_Info);
        BT_DeleteFriend = new JButton();
        BT_DeleteFriend.setHorizontalAlignment(0);
        BT_DeleteFriend.setHorizontalTextPosition(0);
        BT_DeleteFriend.setText("删除好友");
        BT_DeleteFriend.setVerticalAlignment(0);
        panel6.add(BT_DeleteFriend);
        BT_QuitGroup = new JButton();
        BT_QuitGroup.setHorizontalAlignment(0);
        BT_QuitGroup.setHorizontalTextPosition(0);
        BT_QuitGroup.setText("退出群聊");
        BT_QuitGroup.setVerticalAlignment(0);
        panel6.add(BT_QuitGroup);
        topSettingPanel = new JPanel();
        topSettingPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        topSettingPanel.setBackground(new Color(-12763327));
        panel1.add(topSettingPanel, BorderLayout.NORTH);
        BT_AddFriend = new JButton();
        BT_AddFriend.setHorizontalAlignment(0);
        BT_AddFriend.setText("添加好友");
        topSettingPanel.add(BT_AddFriend);
        BT_AddGroup = new JButton();
        BT_AddGroup.setHorizontalAlignment(0);
        BT_AddGroup.setText("添加群聊");
        topSettingPanel.add(BT_AddGroup);
        BT_Setting = new JButton();
        BT_Setting.setHorizontalAlignment(0);
        BT_Setting.setText("设置");
        topSettingPanel.add(BT_Setting);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

    String chatContent = "";

}
